# Generated by Django 2.0.5 on 2018-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_drink', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('recommended_snacks', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snack', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('recommended_drink', models.CharField(max_length=200)),
            ],
        ),
    ]
