# Generated by Django 2.0.5 on 2018-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='recommended_snacks',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='recommended_drink',
        ),
        migrations.AddField(
            model_name='snack',
            name='recommended_drink',
            field=models.ManyToManyField(to='inventory.Drink'),
        ),
    ]
