# Generated by Django 2.0.5 on 2018-05-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180509_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name',
            new_name='sname',
        ),
        migrations.RenameField(
            model_name='snack',
            old_name='name',
            new_name='sname',
        ),
    ]
